
export const APP_DATABASES = ['heroku_3df2b831d9cd2a4'];
// export const APP_DATABASES = [];
export const APP_TABLES = {
    USERS: "auth_users",
    SESSION: "auth_session",
    LOCATION: "location",
    PHARMACY: "pharmacy",
    STOCK: "pharmacy_stock",
    DEPARTMENTS: "classes",
    GROUPS: "groups",
    SUBGROUPS: "sub_group",
    SUPPLIERS: "suppliers",
    CATEGORY: "category",
    SUBSAPAKS: "subsapak",
    SERIES: "degems",
    CATALOG: "catalog",
    UNITSIZE: "unitSize",
    BRANCHTYPE: "branches_type",
    BRANCHES: "branches",
    MIGVANBRANCH: "migvan_branch",
    MIGVANSAPAK: "migvan_sapak",
    PERUK: "peruk",
    SUBBAR: "sub_bar",
    SUBBARGENERAL: "sub_bar_general",
    ASPAKA: "aspaka",
    SUPSIRYUN: "supsiryun",
    SCRMENU: "scrmenu",
    DORDER: "dorder",
    SIBA: "siba",
    SIBARES: "siba_res",
    COUNTERS: "Counters",
    ORDERS: "orders",
    TRANSFER: "transfer",
    INVENTORY: "inventory",
    DESTRUCTION: "destruction",
    DECONSTRUCTION: "deconstruction",
    CONVERSION: "conversion",
    CODECONVERSION: "code_conversion",
    BRANCHNETWORK: "branch_network",
    SIRYUN: "siryun",
    RESERVEDORDER: "reserved_order",
    INTERNALORDERS: "internal_order",
    SINGLESUPPLIERITEM: "single_supplier_item",
    YEDM:"yedm",
    YEDMIV:"yedmiv",
    YEDTZ:"yedtz",
    YED:"yed",
    YEDION:"yedion",
    PRODUCT_CAMPAIGN:"product_campaign",

}
export const DEFUALT_DATABASE = 'heroku_3df2b831d9cd2a4';